version: '3'
services:
  xiaozhi-esp32-server:
    image: xiaozhi-esp32-server:clean
    container_name: xiaozhi-esp32-server-local
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports:
      # ws服务端
      - "8000:8000"
      # 角色API服务端口
      - "8081:8081"
    volumes:
      # 敏感配置文件挂载（从项目根目录的data目录）
      - ../../data/.config.yaml:/opt/xiaozhi-esp32-server/data/.config.yaml
      # 角色配置文件挂载
      - ../../data/roles.json:/opt/xiaozhi-esp32-server/data/roles.json
      # 模型文件挂载，很重要
      - ../../models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
